[theme]
primaryColor = "#E50914"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false
